# -*- coding: utf-8 -*-
"""Final Phase

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lu1jwue3JOWtF3t9_xlRs8mPPYw7ElQZ
"""

import os
import json
import streamlit as st
import pandas as pd
import numpy as np
from scipy.stats import norm
from google import genai
from google.genai import types

# ==========================================
# PAGE CONFIGURATION & BRANDING
# ==========================================
st.set_page_config(
    page_title="SupplyChainSense | AI Inventory Predictor",
    page_icon="📦",
    layout="wide",
    initial_sidebar_state="expanded"
)

st.title("📦 Supply Chain Sense")
st.subheader("Small Business Inventory Predictor & AI Risk Engine")
st.markdown(
    "An intelligent supply chain optimization suite. SupplyChainSense dynamically accepts "
    "**either raw point-of-sale transaction ledgers** or **pre-calculated business summaries**, "
    "extracts true demand distributions, and utilizes Google Gemini 2.5 Flash to simulate live risk adjustments."
)
st.divider()

# ==========================================
# CORE BACKEND FUNCTIONS
# ==========================================
def intelligent_local_fallback(text_input, unique_categories):
    """
    Edge-computed deterministic backup engine to handle cloud network traffic spikes.
    """
    text = text_input.lower()
    detected_delay = 0
    words = text.split()
    for i, word in enumerate(words):
        if word in ['day', 'days', '-day'] and i > 0:
            clean_num = words[i-1].replace('-', '').strip()
            if clean_num.isdigit():
                detected_delay = int(clean_num)
                break

    if detected_delay == 0 and any(k in text for k in ['strike', 'block', 'flood', 'storm', 'delay', 'cyclone']):
        detected_delay = 3

    food_shock = 1.00
    others_shock = 1.00
    if any(k in text for k in ['strike', 'block', 'protest', 'highway']):
        food_shock = 1.15
    elif any(k in text for k in ['cyclone', 'flood', 'storm', 'monsoon', 'weather']):
        food_shock = 1.60
        others_shock = 0.40
    elif any(k in text for k in ['holiday', 'festival', 'celebration', 'christmas']):
        food_shock = 1.30
        others_shock = 1.10

    adjustments = {}
    for cat in unique_categories:
        if any(f_word in cat.lower() for f_word in ['food', 'beverage', 'grocery', 'fresh', 'eat']):
            adjustments[cat] = { "Demand_Shock_Factor": food_shock, "Lead_Time_Delay_Days": detected_delay }
        else:
            adjustments[cat] = { "Demand_Shock_Factor": others_shock, "Lead_Time_Delay_Days": detected_delay }

    return {
        "disruption_summary": f"Local Fail-Safe Active: Inferred operational shifts with an estimated +{detected_delay} day transit bottleneck.",
        "department_adjustments": adjustments
    }

def process_raw_transaction_log(df_raw):
    """
    Automatically converts a raw, messy sales invoice history (like SuperMarket Analysis.csv)
    into a clean, optimized statistical baseline on the fly.
    """
    # 1. Flexible column header alignment mapping
    col_map = {
        'date': 'Date', 'transaction_date': 'Date', 'timestamp': 'Date',
        'product line': 'Department', 'category': 'Department', 'department': 'Department', 'item_type': 'Department',
        'quantity': 'Quantity', 'qty': 'Quantity', 'units_sold': 'Quantity',
        'unit price': 'Unit price', 'price': 'Unit price', 'rate': 'Unit price'
    }

    # Standardize spaces and look for matches
    df_raw.columns = [c.strip() for c in df_raw.columns]
    rename_dict = {c: col_map[c.lower()] for c in df_raw.columns if c.lower() in col_map}
    df_standard = df_raw.rename(columns=rename_dict)

    required_cols = ['Date', 'Department', 'Quantity', 'Unit price']
    if not all(col in df_standard.columns for col in required_cols):
        st.error(f"**Raw CSV Format Error!** Could not automatically align headers. Please ensure your file contains: {required_cols}")
        st.stop()

    # 2. Parse dates safely using mixed regional format checks
    df_standard['Parsed_Date'] = pd.to_datetime(df_standard['Date'], format='mixed')

    # 3. Aggregate individual item lines into total daily sales quantities per category
    daily_matrix = df_standard.groupby(['Parsed_Date', 'Department'])['Quantity'].sum().unstack(fill_value=0)

    # 4. Extract parameters (Mean demand, standard deviation volatility, and average unit price)
    mean_demand = daily_matrix.mean().to_dict()
    std_demand = daily_matrix.std().to_dict()

    # 5. Compile into an inventory baseline matrix using standardized business defaults
    STANDARD_LEAD_TIME = 2
    DEFAULT_SERVICE_LEVEL = 0.95  # 95% target protection level
    z_baseline = norm.ppf(DEFAULT_SERVICE_LEVEL)

    compiled_rows = []
    for category in daily_matrix.columns:
        mu = mean_demand[category]
        sigma = np.nan_to_num(std_demand[category], nan=0.0) # Handle edge cases with zero variance safely

        # Calculate classical Safety Stock and Baseline Reorder Points
        safety_stock = z_baseline * sigma * np.sqrt(STANDARD_LEAD_TIME)
        reorder_point = (mu * STANDARD_LEAD_TIME) + safety_stock

        compiled_rows.append({
            'Department': category,
            'Avg Daily Sales': round(mu, 2),
            'Sales Volatility': round(sigma, 2),
            'Target Service Level': "95%",
            'Reorder Point': round(reorder_point, 2)
        })

    return pd.DataFrame(compiled_rows)

# ==========================================
# INITIALIZE CLOUD API SECURITY
# ==========================================
if "GEMINI_API_KEY" in st.secrets:
    os.environ["GEMINI_API_KEY"] = st.secrets["GEMINI_API_KEY"]
    try:
        client = genai.Client()
    except Exception as e:
        st.error(f"Failed to initialize Gemini Client: {e}")
else:
    st.error("**Security Token Missing!** Please add your `GEMINI_API_KEY` to your Streamlit Advanced Secrets panel.")
    st.stop()


# ==========================================
# DATASET INGESTION & TEMPLATE SIDEBAR
# ==========================================
st.header("Step 1: Ingest Your Business Dataset Profile")

# Layout informational template options inside sidebar
st.sidebar.header("Supported Data Formats")

st.sidebar.markdown("Option A: Raw Transaction Ledgers")
sample_raw_doc = pd.DataFrame({
    "Date": ["01-01-2019", "01-01-2019", "01-02-2019"],
    "Product line": ["Food and beverages", "Home and lifestyle", "Food and beverages"],
    "Quantity": [7, 3, 10],
    "Unit price": [74.69, 46.33, 55.20]
})
st.sidebar.dataframe(sample_raw_doc, hide_index=True)

st.sidebar.markdown("### Option B: Pre-Calculated Profiles")
sample_summary_doc = pd.DataFrame({
    "Department": ["Food and beverages", "Health and beauty"],
    "Avg Daily Sales": [324.5, 142.1],
    "Sales Volatility": [45.2, 18.9],
    "Target Service Level": ["95%", "95%"],
    "Reorder Point": [720, 310]
})
st.sidebar.dataframe(sample_summary_doc, hide_index=True)

col_info, col_box = st.columns([1, 1])

with col_info:
    st.markdown("""
    SupplyChainSense reads individual transaction lines or summary matrices.

    * **If you upload raw invoices:** The engine automatically clean dates, groups transactions by category, aggregates daily sums, and extracts the statistical volatility matrices ($\sigma$) instantly.
    * **If you upload a summary sheet:** Ensure headers contain `Department`, `Avg Daily Sales`, `Sales Volatility`, and `Reorder Point`.
    """)

with col_box:
    uploaded_file = st.file_uploader("Upload your sales ledger spreadsheet file (.CSV format):", type=["csv"])

    # Fallback option to let judges check data without uploading files manually
    DEFAULT_BACKUP = "SuperMarket Analysis.csv"
    run_demo_flag = False

    if uploaded_file is None:
        if os.path.exists(DEFAULT_BACKUP):
            if st.button("Ingest Raw Supermarket Ledger Dataset Demo", use_container_width=True):
                run_demo_flag = True
        else:
            st.info("System Idle: Waiting for a business data file upload above to unlock optimization grids.")
            st.stop()

# Load and identify matrix formats dynamically
if uploaded_file is not None:
    df_raw_input = pd.read_csv(uploaded_file)
elif run_demo_flag or (uploaded_file is None and os.path.exists(DEFAULT_BACKUP)):
    df_raw_input = pd.read_csv(DEFAULT_BACKUP)
    st.caption("Running in Demo Mode using raw historical transaction invoice logs.")

# DETECT SCHEMA & RUN AUTOMATIC PIPELINES
summary_columns = ['Avg Daily Sales', 'Sales Volatility', 'Reorder Point']
is_precalculated = all(col in df_raw_input.columns for col in ['Department'] + summary_columns or [c in df_raw_input.columns for c in ['Product line']])

if 'Department' not in df_raw_input.columns and 'Product line' in df_raw_input.columns:
    df_raw_input = df_raw_input.rename(columns={'Product line': 'Department'})

if is_precalculated and 'Avg Daily Sales' in df_raw_input.columns:
    # Mode 1: Data is precalculated, use it straight away
    df_baseline = df_raw_input.copy()
    st.success("Summary Profile detected. Data loaded directly into risk matrices.")
else:
    # Mode 2: Raw transaction data detected. Run dynamic cleaning and processing.
    with st.spinner("⚡ Raw Transaction log detected. Executing dynamic time-series aggregation and statistical parameter cleaning..."):
        df_baseline = process_raw_transaction_log(df_raw_input)
    st.success(f"Raw transaction history ledger processed! Discovered {len(df_baseline)} unique business product categories.")

# Render baseline table for transparency
with st.expander("View Processed Operational Baseline Data Profile", expanded=False):
    st.dataframe(df_baseline, use_container_width=True, hide_index=True)

st.divider()


# ==========================================
# LIVE EVENT FEED & ACTION CONTROL
# ==========================================
st.header("Step 2: Live Event Feed & Operational Stream")
st.markdown(
    "Provide any live macro-disruption intelligence feed, cargo freight logistics warning, "
    "or regional incident description below. The core AI architecture will dynamically analyze "
    "risk scales and instantly recalculate your probability distributions."
)

user_news_input = st.text_area(
    "Real-World Operational Incident Stream Entry Desk:",
    height=120,
    placeholder="Example: Unprecedented monsoons sweep across southern rail transit lines, generating 6-day delivery delays and initiating widespread household pantry stocking surges..."
)

# Core Pipeline Trigger Button
if st.button("Execute Optimization Models", type="primary", use_container_width=True):
    if not user_news_input.strip():
        st.warning("Execution Interrupted: Please enter a real-world news event description to evaluate.")
    else:
        status_tracker = st.empty()

        with status_tracker.container():
            st.info("**Step 1:** Dispatching unstructured parameters to Google Gemini cloud optimization matrix...")

        risk_payload = None
        current_categories = df_baseline['Department'].unique().tolist()

        try:
            baseline_summary_string = df_baseline[['Department', 'Avg Daily Sales', 'Reorder Point']].to_string(index=False)

            prompt = f"""
            You are a chief AI Logistics Risk Controller tracking an asset operations network with these specific channels: {current_categories}.
            Deconstruct this real-world operational incident entry and extract systemic numerical modifiers for each category.

            ### CURRENT BUSINESS OPERATIONAL DATA PROFILE:
            {baseline_summary_string}

            ### LIVE ENTERED INCIDENT TEXT:
            "{user_news_input}"

            ### COMPUTATION DIRECTIVES:
            Quantify conditions across these exact parameters for each single department profile:
            1. Demand_Shock_Factor (Float): Multiplier tracking shifting demand velocity. Use 1.00 for normal. Scale above 1.00 for panic spikes, scale below 1.00 for system stoppages.
            2. Lead_Time_Delay_Days (Integer): Additional supply logistics transit delay lag.

            ### COMPILATION SCHEMA CONSTRAINT:
            Return ONLY a raw valid JSON structure matching this format exactly. Do not embed conversational language, text blocks, or markdown backticks. All listed categories must be assigned values: {current_categories}.

            {{
              "disruption_summary": "One clear analytical sentence evaluating the core threat",
              "department_adjustments": {{
                 "{current_categories[0]}": {{ "Demand_Shock_Factor": 1.00, "Lead_Time_Delay_Days": 0 }}
              }}
            }}
            """

            response = client.models.generate_content(
                model='gemini-2.5-flash',
                contents=prompt,
                config=types.GenerateContentConfig(
                    response_mime_type="application/json"
                ),
            )

            risk_payload = json.loads(response.text)
            status_tracker.empty()
            st.success(f"**AI Contextual Assessment:** {risk_payload['disruption_summary']}")

        except Exception as api_err:
            status_tracker.empty()
            st.warning("Gemini Cloud Environment experiencing heavy volumes. Deploying deterministic edge fallback models...")
            risk_payload = intelligent_local_fallback(user_news_input, current_categories)
            st.info(f"**Heuristic Fallback Assessment:** {risk_payload['disruption_summary']}")

        # ==========================================
        # STATISTICAL MATH OVERRIDES ENGINE
        # ==========================================
        try:
            category_mapping = risk_payload['department_adjustments']
            st.markdown("Statistical Distribution Overrides Matrix")

            STANDARD_LEAD_TIME = 2
            calculated_data_store = []

            for index, row in df_baseline.iterrows():
                category_name = row['Department']
                historical_mean = row['Avg Daily Sales']
                historical_sigma = row['Sales Volatility']

                # Parse percent levels robustly (e.g. "95%" or 0.95)
                raw_level = str(row['Target Service Level']).replace('%', '').strip()
                service_probability = float(raw_level) / 100.0 if float(raw_level) > 1.0 else float(raw_level)
                z_value = norm.ppf(service_probability)

                # Fetch modifiers safely
                extracted_override = category_mapping.get(category_name, category_mapping.get(str(category_name), {}))
                shock_multiplier = extracted_override.get('Demand_Shock_Factor', 1.0)
                transit_lag = extracted_override.get('Lead_Time_Delay_Days', 0)

                # Apply Statistical Equations
                new_lead_time_duration = STANDARD_LEAD_TIME + transit_lag
                new_safety_stock = z_value * (historical_sigma * shock_multiplier) * np.sqrt(new_lead_time_duration)
                new_reorder_trigger = ((historical_mean * shock_multiplier) * new_lead_time_duration) + new_safety_stock

                calculated_data_store.append({
                    'Category/Department': category_name,
                    'Baseline ROP': row['Reorder Point'],
                    'Demand Shock (AI)': shock_multiplier,
                    'Logistics Delay': f"+{transit_lag} Days",
                    'Calculated Safety Stock': round(new_safety_stock, 2),
                    'Optimized Reorder Point (ROP)': round(new_reorder_trigger, 2)
                })

            df_final_results = pd.DataFrame(calculated_data_store)
            highest_risk_row = df_final_results.loc[df_final_results['Optimized Reorder Point (ROP)'].idxmax()]

            # Key Metric Display Modules
            metric_col1, metric_col2, metric_col3 = st.columns(3)
            metric_col1.metric("Highest Exposure Channel", highest_risk_row['Category/Department'])
            metric_col2.metric("Peak Target Supply Level", f"{highest_risk_row['Optimized Reorder Point (ROP)']} Units")
            metric_col3.metric("System Configuration Profile", "Live Optimization Active")

            st.write("")

            # Styled Results Matrix
            st.dataframe(
                df_final_results.style.highlight_max(axis=0, subset=['Optimized Reorder Point (ROP)'], color='#ffe3e3'),
                use_container_width=True,
                hide_index=True
            )

            # Compiled Downstream Deployment CSV Generator
            export_csv_binary = df_final_results.to_csv(index=False).encode('utf-8')
            st.download_button(
                label="Download Tailored Inventory Blueprint (.CSV)",
                data=export_csv_binary,
                file_name="supplychainsense_optimized_overrides.csv",
                mime="text/csv",
                type="secondary"
            )

        except Exception as calculation_err:
            st.error(f"Statistical Calculation Component Failure: {calculation_err}")
